version: '3.0'

services:
  app:
    build: .
    user: "1000:1000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
  db:
    image: mysql:5.6.45
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=api_db
      - MYSQL_USER=admin_db
      - MYSQL_PASSWORD=password
      
    volumes:
      - local_db:/var/lib/mysql

volumes:
  local_db: